---
title: "Instacart - parte 1"
author: "Leonardo Giovanelli, Marcelo Franceschini, Rafael Costa, Sérgio Gomes, Viviane Sanchez"
date: '`r Sys.Date()`'
institute: "PADS - Insper"
encoding: "UTF-8"
output: 
 flexdashboard::flex_dashboard:
    storyboard: true
    social: menu
    source: embed
    
---

### Referências

- Análise exploratória [Instacart](https://www.instacart.com/datasets/grocery-shopping-2017)

- [Flexdashbaord](https://rmarkdown.rstudio.com/flexdashboard/using.html#overview)

- https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2




```{r setup, include=FALSE, fig.align = 'center'}

knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE)

library(flexdashboard)
library(plotly)
library(tidyverse)
library(skimr)
library(inspectdf)
library(ggrepel)
library(ggthemes)
library(lubridate)
library(grid)
library(plotly)
library(RcppRoll)


```

- Instacart colors

```{r}

font = 'opensans'

instacart_colors <- c("blue" = "#007bff", 
                      "indigo"= "#6610f2",
                      "purple"= "#6f42c1", 
                      "pink"= "#e83e8c",
                      "red"= "#dc3545",
                      "orange"= "#fd7e14",
                      "yellow"= "#ffc107", 
                      "green"= "#34a31a",
                      "dark-green" = "#0e491f", 
                      "teal" = "#20c997", 
                      "cyan"= "#17a2b8", 
                      "white" = "#fff", 
                      "gray"= "#6c757d", 
                      "gray-dark"= "#343a40",
                      "light-blue"= "#eff9ff", 
                      "dark"= "#343a40")

ic_cols <- function(...){
  cols <- c(...)
  if(is.null(cols))
    return (instacart_colors)
  instacart_colors[cols]
}

instacart_palettes <- list(
  `main`  = ic_cols("green", "orange"),

  `cool`  = ic_cols("blue", "cyan", "indigo"),

  `hot`   = ic_cols("yellow","orange","red"),
  
  `greens` = ic_cols("green", "dark-green"),

  `mixed` = ic_cols("green", "orange", "cyan", "yellow", "red"),

  `contrast`  = ic_cols("orange","light-blue","dark-green")
)

instacart_pal <- function(palette = "main", reverse = FALSE, ...) {
  
  pal <- instacart_palettes[[palette]]

  if (reverse) pal <- rev(pal)

  colorRampPalette(pal, ...)
}

scale_color_instacart <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  pal <- instacart_pal(palette = palette, reverse = reverse)

  if (discrete) {
    discrete_scale("colour", paste0("instacart_", palette), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}

scale_fill_instacart <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  
  pal <- instacart_pal(palette = palette, reverse = reverse)

  if (discrete) {
    discrete_scale("fill", paste0("instacart_", palette), palette = pal, ...)
  } else {
    scale_fill_gradientn(colours = pal(256), ...)
  }
}

```


# Arquivos

```{r}

arquivos <- list.files(path = 'data/', 
                       pattern = "*.csv",
                       full.names = TRUE) %>% sort()

aisles_raw <- read_csv(arquivos[1])

departments_raw <- read_csv(arquivos[2])

#op_prior_raw <- read_csv(arquivos[3])

#op_train_raw <- read_csv(arquivos[4])

orders_raw <- read_csv(arquivos[5])

products_raw <- read_csv(arquivos[6])


```

## Ajuste da base

```{r}

orders <- orders_raw %>% 
  filter(eval_set != 'test') %>% 
  filter(order_number != 1) %>% 
  arrange(user_id, order_number) %>% 
  mutate(order_hour_of_day = as.numeric(order_hour_of_day),
         w_day = wday(if_else(order_dow == 0, 7, order_dow), label = TRUE)
         #days_since_prior_order = if_else(is.na(days_since_prior_order), 0,
                                          #days_since_prior_order)
         ) %>% 
  group_by(user_id) %>% 
  mutate(days_ma = roll_mean(days_since_prior_order, 5, fill = NA, na.rm = T)) %>% 
  ungroup() %>% 
  glimpse

  
orders %>% 
  filter(is.na(days_since_prior_order)) %>% 
  group_by(order_number) %>% 
  count()

```


```{r}

orders %>% 
  na.omit() %>% 
  ggplot(aes(x = days_ma)) +
  geom_bar(fill = ic_cols('dark-green')) +
  geom_vline(xintercept = 8, color = ic_cols('orange'), 
             linetype = 'dashed') +
  theme_minimal()


```


## Grupo de usuários que fizeram menos de 10 compras

```{r}

orders_count <- orders %>% 
  #filter(days_since_prior_order < 30) %>% 
  group_by(user_id) %>% 
  count() %>% 
  transmute(compras = n)

orders2 <- orders %>% 
  left_join(orders_count, by = 'user_id') %>% 
  mutate(abaixo_10 = if_else(compras <= 10, 'Menos de 10 pedidos', 'Mais de 10 pedidos'))
  



```

# Graficos

## Frequência de compra

```{r}

orders2 %>% 
  group_by(w_day) %>% 
  summarise(n = n()) %>% 
  mutate(p = n/sum(n)) %>% 
  ggplot(aes(w_day, p)) +
  geom_col(fill = ic_cols("light-blue")) +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_color_instacart() +
  labs(title = 'Frequência total de pedidos',
       x = 'Dia da semana') + 
  theme_minimal()


orders2 %>% 
  group_by(abaixo_10, w_day) %>% 
  summarise(n = n()) %>% 
  mutate(p = n/sum(n)) %>% 
  ggplot(aes(w_day, p, fill = abaixo_10)) +
  geom_col( position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_instacart() +
  labs(title = 'Frequência de pedidos por grupo de clientes' ,
       x = 'Dia da semana') +
  theme_minimal()



```


## Dias desde a última compra
 
```{r}

orders_grouped <- orders2 %>% 
  group_by(w_day, order_hour_of_day, abaixo_10) %>% 
  summarise(avg_compras = mean(compras, na.rm = T),
            avg_days = mean(days_since_prior_order, na.rm = T))

sc1 <- scale_fill_viridis_c()
sc2 <- scale_fill_viridis_c()

avg_dias_total <- orders_grouped %>% 
  ggplot(aes(y = w_day, x = order_hour_of_day, fill = avg_days)) +
  geom_tile() +
  scale_fill_paletteer_c("viridis::viridis")

avg_dias_groups <- orders_grouped %>% 
  ggplot(aes(y = w_day, x = order_hour_of_day, fill = avg_days)) +
  geom_tile() + 
  facet_wrap(~abaixo_10, nrow = 2) +
  scale_fill_viridis_c() +
  #scale_fill_instacart(discrete = FALSE, palette = "greens") +
  labs(y = '', x = 'Horário', fill = 'Média de dias') +
  theme_minimal()

ggplotly(avg_dias_groups)

```


### Pedidos

```{r avg_days}


```


```{r avg_days_10, echo = FALSE}

orders_count <- orders %>% 
  group_by(user_id) %>% 
  count() %>% 
  transmute(compras = n)

orders_count_10 <- orders_count %>% 
              filter(compras <= 10)

avg_days_10 <- orders %>% 
  semi_join(orders_count_10, by = 'user_id') %>% 
  group_by(order_dow, order_hour_of_day) %>% 
  summarise(avg_days = mean(days_since_prior_order, na.rm = T)) %>% 
  pivot_wider(names_from = order_hour_of_day, values_from = avg_days) %>% 
  ungroup()


d3heatmap(avg_days_10, scale = 'column')

```

***
comentários
Premissas

### Produtos

### 
 