---
title: "Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: lumen
    runtime: shiny
---

```{r setup, include=FALSE}

setwd("~/Documents/Data Science/Insper/3 Integradora/instacart/Interatividade")

library(tidyverse)
library(tidymodels)
library(inspectdf)
library(skimr)
library(treemap)
library(d3treeR)
library(ggiraphExtra)
library(ggthemes)
library(janitor)
library(lubridate)
library(grid)
library(shiny)
library(factoextra)

theme_set(theme_minimal())
theme_update(text = element_text(family = "Brandon Text"),
             plot.title = element_text(face = "bold"))

source('../instacart_palette.R')

options(pillar.sigfig = 1)

```


```{r global}

arquivos <- list.files(path = '../data/', 
                       pattern = "*.csv",
                       full.names = TRUE) %>% sort()

base_aisles <- read_csv(arquivos[1])

base_dept <- read_csv(arquivos[2])

base_ord_prior <- read_csv(arquivos[3])

base_ord_train <- read_csv(arquivos[4])

base_orders <- read_csv(arquivos[5])

base_products <- read_csv(arquivos[6])

# Functions ----------------------------------

x4 <- function(x) x^4

x_4 <- function(x) sqrt(sqrt(x))

x2 <- function(x) x^2

x_2 <- function(x) sqrt(x)

# Wrangling ----------------------------------

## Heatmaps -----------

prod_ord_cart2 <- read_csv("../output/prod_ord_cart2.csv")

prod_ord_cart_rec2 <- read_csv("../output/prod_ord_cart_rec2.csv")

prod_ord_cart2_list <- read_csv( "../output/prod_ord_cart2_list.csv")

prod_ord_cart_rec2_list <- read_csv("../output/prod_ord_cart_rec2_list.csv")

n_prod <- c(10:100)

## Clusters ------------

source("clusters.R")

```



Heatmaps
=====================================  


Parâmetros {.sidebar}
-----------------------------------------------------------------------

### Parâmetros

```{r}



selectInput("funcao","Transformação da escala", choices = c("Linear", "Quadrado", "Raiz Quadrada", 
                                                  "Quarta Potência", "Raiz Quarta"),
                                            selected = "Quadrado")

sliderInput("slider_n_prod", "Número de produtos", 
                                         min(n_prod),
                                         max(n_prod), 
                                         value = 50,
                                         step = 15)


?sliderInput
```


Column 
-----------------------------------------------------------------------
### Churn

```{r}

renderPlot({
        prod_ord_cart2_list2 <- prod_ord_cart2_list[1:input$slider_n_prod,1]
        prod_100_n_rec <- prod_ord_cart2 %>% right_join(prod_ord_cart2_list2)
        
        # "1", "x^2", "sqrt2", "x^4", "sqrt4"
        vline_size <- 5
        label_size <- min(7 + (2 * 100/input$slider_n_prod),12)
        n_prod1 <- 3.32
        texto1 <- "Média Produtos/Ordem = 3,32"
        if (input$funcao == "Linear"){
            prod_100_n_rec %>%
                ggplot() +
                geom_tile(aes(reorder(product_name,add_to_cart_order,perc), 
                              add_to_cart_order, fill = perc*100)) +
                scale_fill_gradient2(low = "white", 
                                     high = "darkgreen", 
                                     limits = c(0,40)) +
                theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                labs(title = "Produtos x Cart Order para clientes Churn", 
                     fill = "%", x = "Produto", y = "Ordem no carrinho") +
                theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                geom_hline(yintercept = n_prod1, color = "orange") +
                scale_y_continuous(limits = c(0,30), expand = c(0,0)) +
                geom_text(aes(x = 5, y = n_prod1+0.1, label = texto1 ), 
                          size = vline_size, color = 'orange', hjust = 0, vjust = 0)
        } else {
            if (input$funcao == "Quadrado"){
                prod_100_n_rec %>% ggplot() +
                    geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                    scale_fill_gradient2(low = "white", 
                                         high = "darkgreen", 
                                         limits = c(0,40),
                                         trans = scales::trans_new(name = "quad",
                                                                   transform = x2, inverse = x_2)) +
                    theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                    labs(title = "Produtos x Ordem no carrinho para clientes Churn", 
                         fill = "%", x = "Produto", y = "Ordem no carrinho") +
                    theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                    geom_hline(yintercept = n_prod1, color = "orange") +
                    scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                    geom_text(aes(x = 5, y = n_prod1+0.1, label = texto1 ),
                              size = vline_size, color = 'orange', hjust = 0, vjust = 0)
            } else {
                if (input$funcao == "Raiz Quadrada"){
                    prod_100_n_rec %>% ggplot() +
                        geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                        scale_fill_gradient2(low = "white", 
                                             high = "darkgreen", 
                                             limits = c(0,40),
                                             trans = scales::trans_new(name = "quad",
                                                                       transform = x_2, inverse = x2))+
                        theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                        labs(title = "Produtos x Ordem no carrinho para clientes Churn", 
                             fill = "%", x = "Produto", y = "Ordem no carrinho") +
                        theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                        geom_hline(yintercept = n_prod1, color = "orange") +
                        scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                        geom_text(aes(x = 5, y = n_prod1+0.1, label = texto1 ), 
                                  size = vline_size, color = 'orange', hjust = 0, vjust = 0)
                } else {
                    if (input$funcao == "Quarta Potência"){
                        prod_100_n_rec %>% ggplot() +
                            geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                            scale_fill_gradient2(low = "white", 
                                                 high = "darkgreen", 
                                                 limits = c(0,40),trans = scales::trans_new(name = "quad",transform = x4, inverse = x_4))+
                            theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                            labs(title = "Produtos x Cart_Order para clientes Churn", 
                                 fill = "%", x = "Produto", y = "Ordem Carrinho") +
                            theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                            geom_hline(yintercept = n_prod1, color = "orange") +
                            scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                            geom_text(aes(x = 5, y = n_prod1+0.1, label = texto1 ), 
                                      size = vline_size, color = 'orange', hjust = 0, vjust = 0)
                    } else {
                        if (input$funcao == "Raiz Quarta"){
                            prod_100_n_rec %>% ggplot() +
                                geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                                scale_fill_gradient2(low = "white", 
                                                     high = "darkgreen", 
                                                     limits = c(0,40),
                                                     trans = scales::trans_new(name = "quad",transform = x_4, inverse = x4))+
                                theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                                labs(title = "Heatmap de Produtos x Cart_Order para clientes Churn", fill = "%", x = "Produto", y = "Ordem_Carrinho") +
                                theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                                geom_hline(yintercept = n_prod1, color = "orange") +
                                scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                                geom_text(aes(x = 5, y = n_prod1+0.1, label = texto1 ), size = vline_size, color = 'orange', hjust = 0, vjust = 0)
                        }
                    }
                }
            }
        }


    })

```


### Clientes Recorrentes

```{r}

renderPlot({
        prod_ord_cart_rec2_list <- prod_ord_cart_rec2_list[1:input$slider_n_prod,1]
        prod_100_rec <- prod_ord_cart_rec2 %>% right_join(prod_ord_cart_rec2_list)
        vline_size <- 5
        n_prod2 <- 7.13
        label_size <- min(7 + (2 * 100/input$slider_n_prod),12)
        texto2 <- "Média Produtos/Ordem = 7,13"
        if (input$funcao == "Linear"){
            prod_100_rec %>% ggplot() +
                geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                scale_fill_gradient2(low = "white", 
                                     high = "darkgreen", 
                                     limits = c(0,40))+
                theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                labs(title = "Produtos x Ordem no carrinho para clientes Recorrentes", 
                     fill = "%", x = "Produto", y = "Ordem no carrinho") +
                theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                geom_hline(yintercept = n_prod2, color = "orange") +
                scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                geom_text(aes(x = 5, y = n_prod2+0.1, label = texto2 ), 
                          size = vline_size, color = 'orange', hjust = 0, vjust = 0)
        } else {
            if (input$funcao == "Quadrado"){
                prod_100_rec %>% ggplot() +
                    geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                    scale_fill_gradient2(low = "white", 
                                         high = "darkgreen", 
                                         limits = c(0,40),
                                         trans = scales::trans_new(name = "quad", transform = x2, 
                                                                   inverse = x_2))+
                    theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                    labs(title = "Produtos x Ordem no carrinho para clientes Recorrentes", 
                         fill = "%", x = "Produto", y = "Ordem no carrinho") +
                    theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                    geom_hline(yintercept = n_prod2, color = "orange") +
                    scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                    geom_text(aes(x = 5, y = n_prod2+0.1, label = texto2 ), 
                              size = vline_size, color = 'orange', hjust = 0, vjust = 0)
            } else {
                if (input$funcao == "Raiz Quadrada"){
                    prod_100_rec %>% ggplot() +
                        geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                        scale_fill_gradient2(low = "white", 
                                             high = "darkgreen", 
                                             limits = c(0,40),
                                             trans = scales::trans_new(name = "quad",
                                                                       transform = x_2, inverse = x2))+
                        theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                        labs(title = "Produtos x Ordem no carrinho para clientes Recorrentes", 
                             fill = "%", x = "Produto", y = "Ordem no carrinho") +
                        theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                        geom_hline(yintercept = n_prod2, color = "orange") +
                        scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                        geom_text(aes(x = 5, y = n_prod2+0.1,
                                      label = texto2 ),
                                  size = vline_size, color = 'orange', hjust = 0, vjust = 0)
                } else {
                    if (input$funcao == "Quarta Potência"){
                        prod_100_rec %>% ggplot() +
                            geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                            scale_fill_gradient2(low = "white", 
                                                 high = "darkgreen", 
                                                 limits = c(0,40),trans = scales::trans_new(name = "quad",transform = x4, inverse = x_4))+
                            theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                            labs(title = "Produtos x Ordem no carrinho para clientes Recorrentes", 
                                 fill = "%", x = "Produto", y = "Ordem no carrinho") +
                            theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                            geom_hline(yintercept = n_prod2, color = "orange") +
                            scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                            geom_text(aes(x = 5, y = n_prod2+0.1, label = texto2 ), size = vline_size, color = 'orange', hjust = 0, vjust = 0)
                    } else {
                        if (input$funcao == "Raiz Quarta"){
                            prod_100_rec %>% ggplot() +
                                geom_tile(aes(product_name,add_to_cart_order, fill = perc*100)) +
                                scale_fill_gradient2(low = "white", 
                                                     high = "darkgreen", 
                                                     limits = c(0,40),trans = scales::trans_new(name = "quad",transform = x_4, inverse = x4))+
                                theme(axis.text.x = element_text(angle = 90, size = label_size, hjust = 1)) +
                                labs(title = "Produtos x Ordem no carrinho para clientes Recorrentes", 
                                     fill = "%", x = "Produto", y = "Ordem no carrinho") +
                                theme(axis.text.x = element_text(hjust = 1.0, vjust = 0.3)) + 
                                geom_hline(yintercept = n_prod2, color = "orange") +
                                scale_y_continuous(limits = c(0,30),expand = c(0,0)) +
                                geom_text(aes(x = 5, y = n_prod2+0.1, label = texto2 ), 
                                          size = vline_size, color = 'orange', hjust = 0, vjust = 0)
                        }
                    }
                }
            }
        }
        
        
    })


```


Clusters
=====================================  

Parâmetros {.sidebar}
-----------------------------------------------------------------------

### Parâmetros

```{r}

sliderInput("k", "Número de Clusters",
                        min = 1,
                        max = 10,
                        value = 4)


```

Column 
-----------------------------------------------------------------------
### Clusters

```{r}

renderPlot({
        # generate bins based on input$bins from ui.R
        clust_kmean <- base_k_user[,c(2:ncol(base_k_user))] %>% scale() %>% hkmeans(k = input$k)
        
        
        # Calculando os perfis dos clusters
        # dados_clusters <- (clust_kmean$centers * (clust_kmean$data %>% attr("scaled:scale"))) + (clust_kmean$data %>% attr("scaled:center"))
        
        dados_clusters <- clust_kmean$centers
        
        # A partir da análise é possível definir o perfil dos clusters, para poder dar um nome aos mesmos
        # dados_clusters <- tibble(cluster = rownames(dados_clusters), nome_cluster = c("Compra_Quant","Churn","Fiel_e_Recorrente","Novo_com_Potencial")) %>% bind_cols(as_tibble(dados_clusters))
        dados_clusters <- tibble(cluster = rownames(dados_clusters)) %>% bind_cols(as_tibble(dados_clusters))
        
        spider <- dados_clusters %>% ggRadar(aes(x = c(n_compras,
                                                       t_mean,
                                                       mean_prod_cart,
                                                       mean_peso_cart,
                                                       mean_rec_fat),
                                                 facet = cluster), 
                                             interactive = F,
                                             size = 1.5,
                                             legend.position = "right"
                                             )
        spider
    })


```

### connection

```{r}

renderPrint({
        clust_kmean <- base_k_user[,c(2:ncol(base_k_user))] %>% scale() %>% hkmeans(k = input$k)
        (clust_kmean$centers * (clust_kmean$data %>% attr("scaled:scale"))) 
                            + (clust_kmean$data %>% attr("scaled:center")) %>% 
                                filter(cluster = input$plot_dblclick$panelvar1)
        clust_kmean$size[as.numeric(input$plot_dblclick$panelvar1)]
    })

```

### Produtos

```{r}

renderD3tree3({
        clust_kmean <- base_k_user[,c(2:ncol(base_k_user))] %>% scale() %>% hkmeans(k = input$k)
        base_graf2 <- base_k_user %>%
                            bind_cols(cluster = clust_kmean$cluster) %>%
                            filter(cluster == as.numeric(input$plot_dblclick$panelvar1))
        # base_ord_geral_all %>%
        #     right_join(base_graf2 %>% select(user_id)) %>%
        #     group_by(aisle) %>%
        #     summarise(contagem = n()) %>%
        #     arrange(desc(contagem)) %>%
        #     top_n(10) %>%
        #     ggplot(aes(x = reorder(aisle,desc(contagem)), y = contagem)) +
        #     geom_col(color = "darkorange", fill = "darkgreen")+
        #     theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        #     scale_y_log10()
        cores <- unname(instacart_colors)
        base_ord_geral_all %>%
            right_join(base_graf2 %>% select(user_id)) %>%
            group_by(aisle, product_name) %>%
            summarise(contagem = n()) %>%
            arrange(desc(contagem)) %>%
            data.frame() %>%
            slice_head(n = 50) %>% 
            treemap(base_ord_geral_all,
                    index=c("aisle","product_name"),
                    vSize="contagem",
                    type="index",
                    # palette = "Set2",
                    palette = cores[1:length(cores)],
                    bg.labels=c("white"),
                    align.labels=list(
                        c("center", "center"), 
                        c("right", "bottom")
                    )
            ) %>% d3tree2(rootname = "Principais Produtos")
        # make it interactive ("rootname" becomes the title of the plot):
        # inter <- d3tree2(p, rootname = "Pricipais Produtos")
        # inter
                        
    })

```



